// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://btnioyywtmuyacyjhsit.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ0bmlveXl3dG11eWFjeWpoc2l0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MDA2MjksImV4cCI6MjA2NTQ3NjYyOX0.2tV_7h0mBnWGyNTY-ijnA64bym-5jX4MDKuoF5cyyLI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);